name: flu_circulating_frequencies

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - altair=6.2
  - biopython=1.88
  - black
  - matplotlib=3.11
  - pandas=2.3
  - python=3.14
  - regex=2026.7
  - ruff
  - snakefmt
  - snakemake=9.25
