name: library_design
channels:
    - conda-forge
    - bioconda
dependencies:
    - marimo=0.23.1
    - matplotlib=3.10.8
    - pandas=2.2.3
    - ruamel.yaml=0.18.16
    - snakemake=9.19
    - snakemake-executor-plugin-slurm=2.6.0
