"""Aggregation of sera metadata, QC of the final titers, and plots of those titers."""


rule aggregate_sera_metadata:
    """Aggregate and validate sera metadata from multiple cohorts."""
    input:
        csvs=config["sera_metadata"],
    output:
        csv="results/sera_metadata/all_sera_metadata.csv",
    log:
        "results/logs/aggregate_sera_metadata.txt",
    conda:
        "../seqneut-pipeline/environment.yml"
    script:
        "../scripts/aggregate_sera_metadata.py"


rule process_final_titer_data:
    """Process and QC final titer data for each group."""
    input:
        sera_metadata=rules.aggregate_sera_metadata.output.csv,
        viral_library=lambda wc: config["viral_libraries"][
            config["process_final_titer_data"]["viral_library"]
        ],
        titers="results/aggregated_titers/titers_{group}.csv",
    output:
        titers="results/final_titer_data/{group}_titers.csv",
        sera="results/final_titer_data/{group}_sera.csv",
        sera_multicohort="results/final_titer_data/{group}_sera_multicohort.csv",
        viruses="results/final_titer_data/{group}_viruses.csv",
        titers_summarized="results/final_titer_data/{group}_titers_summarized_by_virus.csv",
        summary="results/final_titer_data/{group}_summary.txt",
    log:
        "results/logs/process_final_titer_data_{group}.txt",
    conda:
        "../seqneut-pipeline/environment.yml"
    params:
        config=config["process_final_titer_data"],
    script:
        "../scripts/process_final_titer_data.py"


rule plot_titer_summaries:
    """Create interactive Altair titer summary plots for each serum group."""
    input:
        marimo_nb="notebooks/plot_titer_summaries.py",
        titers_csv=rules.process_final_titer_data.output.titers,
        sera_csv=rules.process_final_titer_data.output.sera,
        sera_multicohort_csv=rules.process_final_titer_data.output.sera_multicohort,
        viruses_csv=rules.process_final_titer_data.output.viruses,
    output:
        marimo_html="results/titer_plots/{group}_plot_titer_summaries_{orientation}.html",
        context_pickle="results/titer_plots/{group}_plot_titer_summaries_{orientation}_context.pickle",
        chart_htmls=expand(
            "results/titer_plots/{{group}}_{subtype}_{strain_type}_{chart_type}_{{orientation}}.html",
            subtype=config["subtypes"],
            strain_type=["recent", "vaccine"],
            chart_type=["individual_sera", "interquartile_range", "frac_below_cutoff"],
        ),
    log:
        "results/logs/plot_titer_summaries_{group}_{orientation}.txt",
    wildcard_constraints:
        orientation="vertical|horizontal",
    conda:
        "../seqneut-pipeline/environment.yml"
    params:
        recent_vaccine_strains=config["recent_vaccine_strains"],
        circulating_strain_type=config["circulating_strain_type"],
        plot_titer_summaries_params=config["plot_titer_summaries_params"],
        subtypes=config["subtypes"],
        facet_orientation=lambda wc: wc.orientation,
    script:
        "../seqneut-pipeline/scripts/run_marimo_w_context_pickle.py"


# Add titer summary plots to docs HTMLs generated by pipeline
for _group in groups:
    for _orientation in ["vertical", "horizontal"]:
        section_title = (
            f"Interactive charts summarizing {_group} titers ({_orientation})"
        )
        add_htmls_to_docs[section_title] = {
            "Notebook making interactive charts": f"results/titer_plots/{_group}_plot_titer_summaries_{_orientation}.html"
        } | {
            f"{_subtype} {_strain_type} strains {_chart_type}": f"results/titer_plots/{_group}_{_subtype}_{_strain_type}_{_chart_type}_{_orientation}.html"
            for _subtype in config["subtypes"]
            for _strain_type in ["recent", "vaccine"]
            for _chart_type in [
                "individual_sera",
                "interquartile_range",
                "frac_below_cutoff",
            ]
        }


rule plot_fold_changes:
    """Create interactive fold-change titer plots comparing paired sera cohorts."""
    input:
        marimo_nb="notebooks/plot_fold_changes.py",
        titers_csv=lambda wc: (
            f"results/final_titer_data/"
            f"{config['plot_fold_changes'][wc.fold_change_name]['species']}"
            f"_titers.csv"
        ),
        sera_multicohort_csv=lambda wc: (
            f"results/final_titer_data/"
            f"{config['plot_fold_changes'][wc.fold_change_name]['species']}"
            f"_sera_multicohort.csv"
        ),
        viruses_csv=lambda wc: (
            f"results/final_titer_data/"
            f"{config['plot_fold_changes'][wc.fold_change_name]['species']}"
            f"_viruses.csv"
        ),
    output:
        marimo_html="results/titer_plots/{fold_change_name}_plot_fold_changes_{orientation}.html",
        context_pickle="results/titer_plots/{fold_change_name}_plot_fold_changes_{orientation}_context.pickle",
        chart_htmls=expand(
            "results/titer_plots/{{fold_change_name}}_{subtype}_{strain_type}_{chart_type}_{{orientation}}.html",
            subtype=config["subtypes"],
            strain_type=["recent", "vaccine"],
            chart_type=["individual_sera", "interquartile_range"],
        ),
    log:
        "results/logs/plot_fold_changes_{fold_change_name}_{orientation}.txt",
    wildcard_constraints:
        fold_change_name="|".join(config.get("plot_fold_changes", {})),
        orientation="vertical|horizontal",
    conda:
        "../seqneut-pipeline/environment.yml"
    params:
        recent_vaccine_strains=config["recent_vaccine_strains"],
        circulating_strain_type=config["circulating_strain_type"],
        plot_titer_summaries_params=config["plot_titer_summaries_params"],
        subtypes=config["subtypes"],
        fold_change_config=lambda wc: config["plot_fold_changes"][wc.fold_change_name],
        facet_orientation=lambda wc: wc.orientation,
    script:
        "../seqneut-pipeline/scripts/run_marimo_w_context_pickle.py"


# Add fold-change plots to docs HTMLs generated by pipeline
_fold_change_docs = {}
for _fc_name, _fc_config in config.get("plot_fold_changes", {}).items():
    for _orientation in ["vertical", "horizontal"]:
        _sub_key = f"{_fc_config['title']} ({_orientation})"
        _fold_change_docs[_sub_key] = {
            "Notebook making fold-change charts": f"results/titer_plots/{_fc_name}_plot_fold_changes_{_orientation}.html"
        } | {
            f"{_subtype} {_strain_type} strains {_chart_type}": f"results/titer_plots/{_fc_name}_{_subtype}_{_strain_type}_{_chart_type}_{_orientation}.html"
            for _subtype in config["subtypes"]
            for _strain_type in ["recent", "vaccine"]
            for _chart_type in ["individual_sera", "interquartile_range"]
        }
if _fold_change_docs:
    add_htmls_to_docs["Fold-change charts"] = _fold_change_docs


# ENTRIES COMMENTED OUT FOR NOW AS NO TITER DATA ADDED YET
analyze_titers_outputs = [
    # aggregated sera metadata
    # rules.aggregate_sera_metadata.output.csv,
    # final processed titer data
    # *expand(
    #     "results/final_titer_data/{group}_{output_type}.csv",
    #     group=groups,
    #     output_type=[
    #         "titers",
    #         "sera",
    #         "sera_multicohort",
    #         "viruses",
    #         "titers_summarized_by_virus",
    #     ],
    # ),
    # *expand(rules.process_final_titer_data.output.summary, group=groups),
    # titer summary plots
    # *expand(
    #     rules.plot_titer_summaries.output.marimo_html,
    #     group=groups,
    #     orientation=["vertical", "horizontal"],
    # ),
    # fold-change titer plots
    # *expand(
    #     rules.plot_fold_changes.output.marimo_html,
    #     fold_change_name=config.get("plot_fold_changes", {}),
    #     orientation=["vertical", "horizontal"],
    # ),
]
