"""QC of the viral library itself, as opposed to the neutralization titers.

Currently the composition of the library pools; the single-well infections will also go
here.

"""

# miscellaneous plate whose barcode counts each pool is analyzed from
pool_plates = {
    pool: pool_d["miscellaneous_plate"]
    for (pool, pool_d) in config["analyze_pools"].items()
}


rule analyze_pool:
    """Analyze the composition of a library pool and get the re-pooling volumes."""
    input:
        counts=lambda wc: expand(
            rules.miscellaneous_plate_count_barcodes.output.counts,
            misc_plate=pool_plates[wc.pool],
            well=miscellaneous_plates[pool_plates[wc.pool]]["wells"],
        ),
        fates=lambda wc: expand(
            rules.miscellaneous_plate_count_barcodes.output.fates,
            misc_plate=pool_plates[wc.pool],
            well=miscellaneous_plates[pool_plates[wc.pool]]["wells"],
        ),
        invalid=lambda wc: expand(
            rules.miscellaneous_plate_count_barcodes.output.invalid,
            misc_plate=pool_plates[wc.pool],
            well=miscellaneous_plates[pool_plates[wc.pool]]["wells"],
        ),
        samples_csv=lambda wc: config["miscellaneous_plates"][pool_plates[wc.pool]][
            "samples_csv"
        ],
        viral_library=lambda wc: config["viral_libraries"][
            miscellaneous_plates[pool_plates[wc.pool]]["viral_library"]
        ],
        neut_standard_set=lambda wc: config["neut_standard_sets"][
            miscellaneous_plates[pool_plates[wc.pool]]["neut_standard_set"]
        ],
    output:
        html="results/library_qc/{pool}_analyze_pool.html",
        repooling_math="results/library_qc/{pool}_repooling_math.csv",
        dropped_strains="results/library_qc/{pool}_dropped_strains.csv",
    log:
        "results/logs/analyze_pool_{pool}.txt",
    wildcard_constraints:
        pool="|".join(config["analyze_pools"]),
    conda:
        "../seqneut-pipeline/environment.yml"
    params:
        date=lambda wc: config["miscellaneous_plates"][pool_plates[wc.pool]]["date"],
        pool_config=lambda wc: config["analyze_pools"][wc.pool],
    script:
        "../scripts/analyze_pool.py"


# Add the pool composition reports to docs HTMLs generated by pipeline, under a heading
# that will also hold the other library QC analyses
if config["analyze_pools"]:
    add_htmls_to_docs["Library quality-control"] = {
        "Composition of the library pools": {
            f"{_pool} ({config['miscellaneous_plates'][pool_plates[_pool]]['date']})": (
                rules.analyze_pool.output.html.format(pool=_pool)
            )
            for _pool in config["analyze_pools"]
        }
    }


# the HTMLs are not listed as they are already inputs to `build_docs`
library_qc_outputs = [
    *expand(rules.analyze_pool.output.repooling_math, pool=config["analyze_pools"]),
    *expand(rules.analyze_pool.output.dropped_strains, pool=config["analyze_pools"]),
]
